/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Recipe = IDL.Record({
  'difficultyLevel' : IDL.Text,
  'cookingTime' : IDL.Nat,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'videoUrl' : IDL.Text,
  'ingredients' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getRecipeByName' : IDL.Func([IDL.Text], [IDL.Opt(Recipe)], ['query']),
  'getRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Recipe = IDL.Record({
    'difficultyLevel' : IDL.Text,
    'cookingTime' : IDL.Nat,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'videoUrl' : IDL.Text,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getRecipeByName' : IDL.Func([IDL.Text], [IDL.Opt(Recipe)], ['query']),
    'getRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };